[package]
name = "A-Level-NEA"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "./core/" }
ray-me = { path = "./ray-me/" }
rayst-engine = { path = "./rayst-engine/" }

[workspace]